<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="774" started-at="2017-12-09T03:04:23Z" finished-at="2017-12-09T03:04:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="774" started-at="2017-12-09T03:04:23Z" finished-at="2017-12-09T03:04:24Z">
      <class name="com.test.sample1.tests.test1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="beforeSuite" is-config="true" duration-ms="9169" started-at="2017-12-09T08:34:14Z" finished-at="2017-12-09T08:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="test1" duration-ms="110" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="aftermethod" is-config="true" duration-ms="6" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="test2" duration-ms="1" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.test.sample1.tests.test1.test2(test1.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="aftermethod" is-config="true" duration-ms="638" started-at="2017-12-09T08:34:23Z" finished-at="2017-12-09T08:34:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.test.sample1.tests.test1@302552ec]" name="afterSuite" is-config="true" duration-ms="75" started-at="2017-12-09T08:34:24Z" finished-at="2017-12-09T08:34:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.sample1.tests.test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
