<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="804" started-at="2017-12-09T03:06:51Z" finished-at="2017-12-09T03:06:52Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="804" started-at="2017-12-09T03:06:51Z" finished-at="2017-12-09T03:06:52Z">
      <class name="com.test.sample1.tests.test1">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="beforeSuite" is-config="true" duration-ms="10896" started-at="2017-12-09T08:36:40Z" finished-at="2017-12-09T08:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="test1" duration-ms="108" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="aftermethod" is-config="true" duration-ms="6" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="test2" duration-ms="37" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:51Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at com.test.sample1.tests.test1.test2(test1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="aftermethod" is-config="true" duration-ms="638" started-at="2017-12-09T08:36:51Z" finished-at="2017-12-09T08:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.test.sample1.tests.test1@323b36e0]" name="afterSuite" is-config="true" duration-ms="79" started-at="2017-12-09T08:36:52Z" finished-at="2017-12-09T08:36:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.sample1.tests.test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
